### ISSUE TITLE
BiasCorrection in AdamW

### ISSUE THREAD

**Issue by Muennighoff** [asappresearch/revisit-bert-finetuning#2]
Great paper, thanks.

Quick question, am I correct to assume that the bias correction has been addressed in the transformers library? It seems that their new AdamW is taking an argument BiasCorrection, which evaluates to True by default, hence using BC.

**Comment by fwu-asapp** [comment]
Thanks! Yes, you are absolutely correct. Bias correction is set as default after RoBERTa was added to the library (precisely in commit ec07cf5a on July 11, 2019). We also acknowledge it in our paper (see footnote 5).

**Comment by Muennighoff** [comment]
Great thanks for the confirmation!
